---
- name: Install ntp
  yum: name=ntp state=installed
  tags: ntp

- name: Ensure ntp is configured
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: make sure ntpd is running and enabled
  service: name=ntpd state=started enabled=yes
  tags: ntp
